### ISSUE TITLE
0.1 Mise en place de l'architecture globale du projet

### ISSUE THREAD

**Issue by loloups** [NitriKx/M2DL-IVVQ-Running-Lama#12]
#11

**Comment by NitriKx** [comment]
- Créer l'arborescences des fichiers dans le projet
- Importer les librairies graphiques pour la partie Web 
- Créer une première page HTML 
- Créer les classes de modèles Utilisateur, ...
- Créer les classes de test + service + controllers même si y a rien à l'intérieur
