### ISSUE TITLE
2.2 Modification du trajet

### ISSUE THREAD

**Issue by chj0455a** [NitriKx/M2DL-IVVQ-Running-Lama#14]
#26

En tant que conducteur, je souhaite modifier un de mes trajet afin de changer les horaires, étapes, nombre de personne, ... du trajet

**Comment by NitriKx** [comment]
En tant que conducteur, je dois pouvoir accéder à l'interface de modification d'un trajet grace à un bouton "Modifier" dans la page "Voir mes trajets"
