### ISSUE TITLE
1.3 Gestion Véhicule 

### ISSUE THREAD

**Issue by loloups** [NitriKx/M2DL-IVVQ-Running-Lama#9]
#10

En tant que membre connecté je souhaite accéder a mon profil afin de modifier ou ajouter un véhicule

**Comment by NitriKx** [comment]
- Classe de domaine
  - int nb_place
  - String marque
  - String modele
  - Date annee
  - int kilometrage
  - TypeVehicule type
    - Enumeration 
- Gestion de la photo ? 
- Service / Véhicule
  - Une seule classe Véhicule sans héritage
- Vue véhicule
